# Hypothesis using matrix

|X1|x2|x3|Y|
|---|---|---|---|
|73|80|75|152|
|93|88|93|185|
|89|91|90|180|
|89|91|90|180|
|96|98|100|196|
|73|66|70|142|

In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

In [3]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [4]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  17914.54 
Prediction:
 [31.547438 42.68851  39.492153 43.051365 33.946415]
10 Cost:  0.9182364 
Prediction:
 [149.9496  184.99345 179.71059 195.74525 142.4882 ]
20 Cost:  0.75113547 
Prediction:
 [150.31082 185.422   180.13576 196.20786 142.81403]
30 Cost:  0.74804115 
Prediction:
 [150.31488 185.42125 180.13795 196.2098  142.81245]
40 Cost:  0.74496436 
Prediction:
 [150.31786 185.41924 180.1389  196.21039 142.80988]
50 Cost:  0.7419035 
Prediction:
 [150.32082 185.4172  180.1398  196.21095 142.80731]
60 Cost:  0.7388631 
Prediction:
 [150.32376 185.41519 180.14072 196.2115  142.80475]
70 Cost:  0.7358352 
Prediction:
 [150.32672 185.4132  180.14165 196.21207 142.80222]
80 Cost:  0.7328252 
Prediction:
 [150.32965 185.4112  180.14256 196.21263 142.79965]
90 Cost:  0.7298347 
Prediction:
 [150.33258 185.40921 180.14346 196.2132  142.79712]
100 Cost:  0.7268561 
Prediction:
 [150.3355  185.4072  180.14436 196.21375 142.79459]
110 Cost:  0.7238874 
Prediction:
 [150.33842 185.40

## Matrix

In [5]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

In [6]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [7]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  9.67602 
Prediction:
 [[155.22758]
 [185.33092]
 [183.25745]
 [200.75066]
 [139.83815]]
10 Cost:  5.395729 
Prediction:
 [[153.39464]
 [183.14217]
 [181.09343]
 [198.3944 ]
 [138.17203]]
20 Cost:  5.3733735 
Prediction:
 [[153.38155]
 [183.14076]
 [181.08464]
 [198.38512]
 [138.17427]]
30 Cost:  5.351205 
Prediction:
 [[153.374  ]
 [183.14597]
 [181.08237]
 [198.38297]
 [138.18153]]
40 Cost:  5.3291183 
Prediction:
 [[153.36649]
 [183.15118]
 [181.08015]
 [198.38084]
 [138.18883]]
50 Cost:  5.307154 
Prediction:
 [[153.35898]
 [183.15637]
 [181.07791]
 [198.37871]
 [138.19608]]
60 Cost:  5.285324 
Prediction:
 [[153.35152]
 [183.16156]
 [181.0757 ]
 [198.37659]
 [138.20331]]
70 Cost:  5.2636237 
Prediction:
 [[153.34406]
 [183.16669]
 [181.07346]
 [198.37444]
 [138.2105 ]]
80 Cost:  5.2420063 
Prediction:
 [[153.33662]
 [183.17184]
 [181.07126]
 [198.37234]
 [138.21771]]
90 Cost:  5.220534 
Prediction:
 [[153.3292 ]
 [183.17697]
 [181.06905]
 [198.37021]
 [138.22485]]
100 Cost