In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

Instructions for updating:
non-resource variables are not supported in the long term


In [5]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


In [6]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

0 Cost: 3305.7485 
Prediction:
 [[ 99.01425 ]
 [119.770706]
 [117.649994]
 [129.50452 ]
 [ 90.07959 ]
 [ 67.98811 ]
 [ 98.27899 ]
 [ 74.85732 ]
 [113.46043 ]
 [107.7672  ]
 [ 93.49449 ]
 [ 92.84668 ]
 [120.3325  ]
 [ 98.031006]
 [ 98.944084]
 [122.70262 ]
 [ 91.92496 ]
 [118.922066]
 [114.38121 ]
 [102.36185 ]
 [115.13089 ]
 [113.45178 ]
 [109.30502 ]
 [ 96.90362 ]
 [123.5239  ]]
10 Cost: 6.0932946 
Prediction:
 [[152.65164 ]
 [184.2394  ]
 [181.17125 ]
 [198.68436 ]
 [139.24753 ]
 [104.23838 ]
 [150.06265 ]
 [113.246735]
 [173.71182 ]
 [163.57559 ]
 [143.38544 ]
 [142.04102 ]
 [185.95837 ]
 [152.58488 ]
 [150.96605 ]
 [188.1234  ]
 [143.88037 ]
 [181.06741 ]
 [176.9458  ]
 [158.34216 ]
 [175.85555 ]
 [173.93234 ]
 [167.20096 ]
 [150.98209 ]
 [190.33783 ]]
20 Cost: 5.935409 
Prediction:
 [[153.02135 ]
 [184.68515 ]
 [181.6097  ]
 [199.16231 ]
 [139.58748 ]
 [104.489845]
 [150.42067 ]
 [113.51245 ]
 [174.12926 ]
 [163.96333 ]
 [143.73033 ]
 [142.38187 ]
 [186.41093 ]
 [152.96057 ]
 [151

In [7]:
print("Your score will be ", sess.run(hypothesis, 
                                      feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[186.42491]]
Other scores will be  [[182.26025]
 [175.55664]]


In [8]:
tf.set_random_seed(777)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.
Instructions for updating:
Queue-base

In [9]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
0 Cost:  2598.893 
Prediction:
 [[105.63413 ]
 [126.47547 ]
 [125.023895]
 [135.61624 ]
 [ 96.54288 ]
 [ 69.79834 ]
 [100.468285]
 [ 73.146675]
 [117.17079 ]
 [106.953476]]
10 Cost:  12.217089 
Prediction:
 [[154.37231 ]
 [185.07695 ]
 [182.75241 ]
 [198.49669 ]
 [141.23367 ]
 [102.764694]
 [147.54459 ]
 [108.05685 ]
 [171.95518 ]
 [157.72067 ]]
20 Cost:  11.8052025 
Prediction:
 [[154.6922  ]
 [185.47464 ]
 [183.1368  ]
 [198.9231  ]
 [141.53386 ]
 [102.99955 ]
 [147.87163 ]
 [108.309875]
 [172.33943 ]
 [158.09494 ]]
30 Cost:  11.731593 
Prediction:
 [[154.68541]
 [185.47955]
 [183.13428]
 [198.92807]
 [141.53448]
 [103.01346]
 [147.88318]
 [108.32898]
 [172.3565 ]
 [158.129  ]]
40 Cost:  11.660123 
Prediction:
 [[154.67644 ]
 [185.4818  ]
 [183.12915 ]
 [198.93016 ]
 [141.53307 ]
 [103.025826]
 [147.89253 ]
 [108.34644 ]
 [172.371   ]
 [158.16061 ]]
50 Cost:  11.58932 
Prediction:
 [[154.66753 ]
 [185.